[package]
name = "shared"
description = "Structs that are used both in the server and the client."
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
ts-rs = "7.0.0"
